server:
  ip: 127.0.0.1
  port: 8111

database:
  username: Reza
  password: TheAlxan
  # this is for persisting to disk
  url: jdbc:h2:~/anymind
  # this is for In-Memory database
  #  url: jdbc:h2:mem:anymind

  # period delay for fixing database late records, milliseconds, 10 * 60  * 1000, currently set to 10 minutes
  fixDelay: 15000